#!/bin/bash

cd $(dirname "$(readlink -f $0)")


SHA=$(git show --oneline -s | awk '{ print $1 }')
TIMESTAMP=$(date +%s)
VERSION=$(cat ../../VERSION.midokura | grep -v ^# | head -1 \
          | sed "s/dev/dev$TIMESTAMP.$SHA/" )

if [ "$1" = "rpm-version" ]; then
    echo $VERSION | awk -F- '{ print $1 }'
    exit
fi

if [ "$1" = "rpm-release" ]; then
    echo $VERSION | awk -F- '{ print $2 }'
    exit
fi

echo $VERSION
